name: productivioapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  get_it: ^7.6.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
  uses-material-design: true

